import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div className="fixed inset-0 bg-gradient-to-br from-blue-400/20 via-white/20 to-purple-500/20 pointer-events-none z-0"></div>
        <div className="flower-layer-2">🌺 💮 🌸 🏵️ 🌼 💐 🌺 🌸 💮 🏵️ 🌼 🌸 💐 🌺 🌸</div>
        <div className="flower-layer-3">🌼 🌸 💮 🌺 🏵️ 💐 🌸 🌺 💮 🏵️ 🌼 🌸 💐 🌺 🌸</div>
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
